name: Upload to S3

on:
  push:
    branches:
      - Deploy  # Trigger this workflow on pushes to the main branch

jobs:
  upload-to-s3:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install AWS CLI
        run: sudo apt-get install awscli
        
      - name: Upload to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "eu-west-2"
        run: |
          aws s3 cp ./static/maps/Tiles s3://mario-map/ --recursive